/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nokia_mj_impl_location_Positioner */

#ifndef _Included_com_nokia_mj_impl_location_Positioner
#define _Included_com_nokia_mj_impl_location_Positioner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nokia_mj_impl_location_Positioner
 * Method:    _getLocation
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_nokia_mj_impl_location_Positioner__1getLocation
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_nokia_mj_impl_location_Positioner
 * Method:    _createPositioner
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_nokia_mj_impl_location_Positioner__1createPositioner
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_nokia_mj_impl_location_Positioner
 * Method:    _cancel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_nokia_mj_impl_location_Positioner__1cancel
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_nokia_mj_impl_location_Positioner
 * Method:    _dispose
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_nokia_mj_impl_location_Positioner__1dispose
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
