/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nokia_mj_impl_location_LAPIManager */

#ifndef _Included_com_nokia_mj_impl_location_LAPIManager
#define _Included_com_nokia_mj_impl_location_LAPIManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nokia_mj_impl_location_LAPIManager
 * Method:    _createFunctionSource
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_nokia_mj_impl_location_LAPIManager__1createFunctionSource
  (JNIEnv *, jobject);

/*
 * Class:     com_nokia_mj_impl_location_LAPIManager
 * Method:    _dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_nokia_mj_impl_location_LAPIManager__1dispose
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
