/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_location_Coordinates */

#ifndef _Included_javax_microedition_location_Coordinates
#define _Included_javax_microedition_location_Coordinates
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_location_Coordinates_DD_MM_SS
#define javax_microedition_location_Coordinates_DD_MM_SS 1L
#undef javax_microedition_location_Coordinates_DD_MM
#define javax_microedition_location_Coordinates_DD_MM 2L
#undef javax_microedition_location_Coordinates_MIN_LATITUDE
#define javax_microedition_location_Coordinates_MIN_LATITUDE -90.0
#undef javax_microedition_location_Coordinates_MAX_LATITUDE
#define javax_microedition_location_Coordinates_MAX_LATITUDE 90.0
#undef javax_microedition_location_Coordinates_MIN_LONGITUDE
#define javax_microedition_location_Coordinates_MIN_LONGITUDE -180.0
#undef javax_microedition_location_Coordinates_MAX_LONGITUDE
#define javax_microedition_location_Coordinates_MAX_LONGITUDE 180.0
#undef javax_microedition_location_Coordinates_BEARING_ZERO
#define javax_microedition_location_Coordinates_BEARING_ZERO 0.0f
#undef javax_microedition_location_Coordinates_BEARING_HALF
#define javax_microedition_location_Coordinates_BEARING_HALF 180.0f
/*
 * Class:     javax_microedition_location_Coordinates
 * Method:    _azimuthTo
 * Signature: (DDDD)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_location_Coordinates__1azimuthTo
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     javax_microedition_location_Coordinates
 * Method:    _distance
 * Signature: (DDDD)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_location_Coordinates__1distance
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
