/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_location_LocationProvider */

#ifndef _Included_javax_microedition_location_LocationProvider
#define _Included_javax_microedition_location_LocationProvider
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_location_LocationProvider_AVAILABLE
#define javax_microedition_location_LocationProvider_AVAILABLE 1L
#undef javax_microedition_location_LocationProvider_TEMPORARILY_UNAVAILABLE
#define javax_microedition_location_LocationProvider_TEMPORARILY_UNAVAILABLE 2L
#undef javax_microedition_location_LocationProvider_OUT_OF_SERVICE
#define javax_microedition_location_LocationProvider_OUT_OF_SERVICE 3L
#ifdef __cplusplus
}
#endif
#endif
