/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_location_LandmarkStore */

#ifndef _Included_javax_microedition_location_LandmarkStore
#define _Included_javax_microedition_location_LandmarkStore
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_location_LandmarkStore_KErrAlreadyExists
#define javax_microedition_location_LandmarkStore_KErrAlreadyExists -11L
#undef javax_microedition_location_LandmarkStore_KErrSessionClosed
#define javax_microedition_location_LandmarkStore_KErrSessionClosed -45L
#undef javax_microedition_location_LandmarkStore_KLandmarkNameLength
#define javax_microedition_location_LandmarkStore_KLandmarkNameLength 255L
/*
 * Class:     javax_microedition_location_LandmarkStore
 * Method:    _addLandmark
 * Signature: (IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_location_LandmarkStore__1addLandmark
  (JNIEnv *, jobject, jint, jint, jint, jstring);

/*
 * Class:     javax_microedition_location_LandmarkStore
 * Method:    _getLandmarks
 * Signature: (II[I)[I
 */
JNIEXPORT jintArray JNICALL Java_javax_microedition_location_LandmarkStore__1getLandmarks
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     javax_microedition_location_LandmarkStore
 * Method:    _getLandmarksFromCategory
 * Signature: (IILjava/lang/String;Ljava/lang/String;[I)[I
 */
JNIEXPORT jintArray JNICALL Java_javax_microedition_location_LandmarkStore__1getLandmarksFromCategory
  (JNIEnv *, jobject, jint, jint, jstring, jstring, jintArray);

/*
 * Class:     javax_microedition_location_LandmarkStore
 * Method:    _getLandmarksFromArea
 * Signature: (IILjava/lang/String;DDDD[I)[I
 */
JNIEXPORT jintArray JNICALL Java_javax_microedition_location_LandmarkStore__1getLandmarksFromArea
  (JNIEnv *, jobject, jint, jint, jstring, jdouble, jdouble, jdouble, jdouble, jintArray);

/*
 * Class:     javax_microedition_location_LandmarkStore
 * Method:    _removeLandmarkFromCategory
 * Signature: (IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_location_LandmarkStore__1removeLandmarkFromCategory
  (JNIEnv *, jobject, jint, jint, jint, jstring);

/*
 * Class:     javax_microedition_location_LandmarkStore
 * Method:    _updateLandmark
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_location_LandmarkStore__1updateLandmark
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     javax_microedition_location_LandmarkStore
 * Method:    _deleteLandmark
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_location_LandmarkStore__1deleteLandmark
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     javax_microedition_location_LandmarkStore
 * Method:    _listCategories
 * Signature: (II[I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_javax_microedition_location_LandmarkStore__1listCategories
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     javax_microedition_location_LandmarkStore
 * Method:    _addCategory
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_location_LandmarkStore__1addCategory
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     javax_microedition_location_LandmarkStore
 * Method:    _deleteCategory
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_location_LandmarkStore__1deleteCategory
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     javax_microedition_location_LandmarkStore
 * Method:    _dispose
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_location_LandmarkStore__1dispose
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
