/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_location_Landmark */

#ifndef _Included_javax_microedition_location_Landmark
#define _Included_javax_microedition_location_Landmark
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javax_microedition_location_Landmark
 * Method:    _createNativePeer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_location_Landmark__1createNativePeer
  (JNIEnv *, jobject, jint);

/*
 * Class:     javax_microedition_location_Landmark
 * Method:    _getName
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javax_microedition_location_Landmark__1getName
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     javax_microedition_location_Landmark
 * Method:    _getDescription
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javax_microedition_location_Landmark__1getDescription
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     javax_microedition_location_Landmark
 * Method:    _getCoordinates
 * Signature: (II[D[F)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_location_Landmark__1getCoordinates
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jfloatArray);

/*
 * Class:     javax_microedition_location_Landmark
 * Method:    _getAddressInfo
 * Signature: (II)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_javax_microedition_location_Landmark__1getAddressInfo
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     javax_microedition_location_Landmark
 * Method:    _setName
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_location_Landmark__1setName
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     javax_microedition_location_Landmark
 * Method:    _setDescription
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_location_Landmark__1setDescription
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     javax_microedition_location_Landmark
 * Method:    _setCoordinates
 * Signature: (II[D[F)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_location_Landmark__1setCoordinates
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jfloatArray);

/*
 * Class:     javax_microedition_location_Landmark
 * Method:    _setAddressInfo
 * Signature: (II[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_location_Landmark__1setAddressInfo
  (JNIEnv *, jobject, jint, jint, jobjectArray);

/*
 * Class:     javax_microedition_location_Landmark
 * Method:    _dispose
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_location_Landmark__1dispose
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
