/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_location_Orientation */

#ifndef _Included_javax_microedition_location_Orientation
#define _Included_javax_microedition_location_Orientation
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_location_Orientation_AZIMUTH
#define javax_microedition_location_Orientation_AZIMUTH 0L
/*
 * Class:     javax_microedition_location_Orientation
 * Method:    _getAzimuthData
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_location_Orientation__1getAzimuthData
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_location_Orientation
 * Method:    _getData
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_location_Orientation__1getData
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_location_Orientation
 * Method:    _dispose
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_location_Orientation__1dispose
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     javax_microedition_location_Orientation
 * Method:    _createNativeHandle
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_location_Orientation__1createNativeHandle
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
